# Site settings
title: Asso Ninja
email: aymerick@asso.ninja
description: Un site web pour votre association
baseurl: ""
url: "http://beta.asso.ninja"

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "README.md"

gems:
  - jekyll-minifier

jekyll-minifier:
  exclude: ['*.html', '*.xml']
